"$schema" = 'https://starship.rs/config-schema.json'
palette = "gruvbox" # !! This feature depends on `starship` >= v1.11.0

[kubernetes]
symbol = "⛵ "
disabled = false
contexts = [
  { context_pattern = "gke_standd-prod_us-central1_standd-prod", style = "red", context_alias = "prod"},
  { context_pattern = "gke_standd-staging_us-central1_standd-staging", style = "green", context_alias = "staging"}
]
[docker_context]
disabled = true
[bun]
disabled = true
[package]
disabled = true
[elixir]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[gcloud]
symbol = "☁️  "
format = '[$symbol($account)@($project)]($style) '
[gcloud.project_aliases]
"standd-prod" = "prod"
"standd-staging" = "staging"
[palettes.24Bit] #Color palette
     col_black="#0A0400" # -- Text inverse
       col_red="#D61E1C" # -- Error/Attention
     col_green="#1DA65A" # -- Success/Time
    col_yellow="#EDBC00" # -- Informational
      col_blue="#0A75AD" # -- User/Hostname bg
   col_magenta="#FF33B8" # -- /tmp directory and Termux Prefix
      col_cyan="#00CEF1" # ~~ Currently unused
col_light_grey="#B0B2B4" # -- Text light
 col_dark_grey="#4F4D4B" # -- bg dark
    col_orange="#E26D0E" # -- Abort/Interrupt
    col_purple="#9010F0" # -- Continuation Prompt
     col_white="#F5FBFF" # -- Text color general
[palettes.gruvbox]
red = "#cc2418"
red-light = "#fb4934"
blue = "#458588"
blue-light = "#83a598"
green = "#98971a"
green-light = "#b8bb26"
yellow = "#d79921"
yellow-light = "#fabd2f"
purple = "#b16286"
purple-light = "#d3869b"
aqua = "#689d6a"
aqua-light = "#8ec07c"
orange = "#d65d0e"
orange-light = "#fe8019"
gray = "#928374"
gray-light = "#a89984"
gray-dark = "#928374"
fg = "#ebdbb2"
fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984"
bg = "#282828"
bg0-h = "#1d2021"
bg0-s = "#32302f"
bg0 = "#282828"
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"
